# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Team Mood, Morale & Health
name: TeamMood
bio: 'With TeamMood, make your team great!'
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: hello@teammood.com
description: 'Some words about feeling good at work.'
logo: https://res.cloudinary.com/teammood/image/upload/b_rgb:ffffff/c_scale,h_48,w_76/v1541855232/logo-1000px_transparent.png
baseurl: "" # the subpath of your site, e.g. /blog
url: https://blog.teammood.com
paginate: 8

author:
  name: Nicolas Deverge
  twitter: ndeverge
twitter:
  username: teammood
  card: summary_large_image
facebook:
  publisher: https://www.facebook.com/teammood
lang: en

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins:
- jekyll-redirect-from
- jekyll-assets
- jekyll-paginate
- jekyll-seo-tag
- jekyll-webp

social:
  name: TeamMood
  links:
    - https://twitter.com/teammood
    - https://www.facebook.com/teammood
    - https://www.linkedin.com/company/teammood/

############################################################
# Site configuration for the WebP Generator Plugin
# https://github.com/sverrirs/jekyll-webp
webp:
  enabled: true
  # List of directories containing images to optimize, nested directories will only be checked if `nested` is true
  img_dir: ["/images/posts","/uploads"]

  # Whether to search in nested directories or not
  nested: true